const {createApp,ref,computed,onMounted,nextTick}=Vue;
const DATA='./data/';
const StockTable={props:['rows'],emits:['pick'],methods:{signed(x){return x==null?'—':(x>=0?'+':'')+Number(x).toFixed(2)}},template:`<table class="table"><thead><tr><th>股票</th><th>现价</th><th>涨跌</th><th>等级</th><th>共振</th><th>机会</th><th>质量</th><th>策略</th></tr></thead><tbody><tr v-for="r in rows" @click="$emit('pick',r)"><td><span class="stock-name">{{r.name}}</span><span class="stock-code">{{r.symbol}}</span></td><td>{{r.price}}</td><td :class="r.change_pct>=0?'up':'down'">{{signed(r.change_pct)}}%</td><td><span class="tag" :class="r.tier==='S'?'s':r.tier==='A'?'a':r.tier==='D'?'d':''">{{r.tier}}</span></td><td>{{r.resonance_count}}</td><td>{{r.opportunity_score}}</td><td>{{r.quality_score}}</td><td><span v-for="k in (r.strategy_keys||[])" class="tag">{{k}}</span></td></tr></tbody></table>`};
createApp({components:{StockTable},setup(){
 const nav=[{id:'home',name:'今日作战',icon:'⌂'},{id:'signals',name:'智能选股',icon:'◎'},{id:'market',name:'市场监控',icon:'◌'},{id:'watch',name:'自选跟踪',icon:'☆'},{id:'risk',name:'组合风控',icon:'◇'},{id:'research',name:'策略实验',icon:'▣'},{id:'news',name:'实时情报',icon:'◈'},{id:'settings',name:'系统设置',icon:'⚙'}];
 const tab=ref('home'),query=ref(''),filter=ref(''),tierFilter=ref('all'),strategyFilter=ref('all'),sort=ref('opp'),signals=ref({items:[]}),market=ref({}),news=ref([]),backtest=ref({}),selected=ref(null),watchlist=ref(JSON.parse(localStorage.getItem('quant_watchlist')||'[]')),account=ref(Number(localStorage.getItem('quant_account')||1000000)),riskPct=ref(Number(localStorage.getItem('quant_risk_pct')||1)),maxPos=ref(Number(localStorage.getItem('quant_max_pos')||8)),dark=ref(localStorage.getItem('quant_dark')==='1'),auto=ref(true),lastRefresh=ref('加载中'),loading=ref(false);
 const catalog=computed(()=>({A:'低位启动',B:'主升突破',C:'回踩二波',D:'筹码结构穿透',E:'龙头强度',F:'超跌反转',G:'量价异动',H:'风险拦截'}));
 const rows=computed(()=>signals.value.items||[]); const healthy=computed(()=>!!market.value.updated_at&&!!market.value.scanned); const breadth=computed(()=>market.value.breadth||{});
 const breadthAdv=computed(()=>{const t=(breadth.value.advancers||0)+(breadth.value.decliners||0);return t?Math.round(breadth.value.advancers/t*100):50}); const breadthDec=computed(()=>100-breadthAdv.value);
 const tier=k=>rows.value.filter(x=>x.tier===k).length; const count=k=>rows.value.filter(x=>(x.strategy_keys||[]).includes(k)).length;
 const top=computed(()=>rows.value.filter(x=>x.tier==='S'||x.tier==='A').slice(0,10));
 const filtered=computed(()=>{let a=rows.value.filter(x=>!filter.value||(`${x.name}${x.symbol}`).includes(filter.value));if(tierFilter.value!=='all')a=a.filter(x=>x.tier===tierFilter.value);if(strategyFilter.value!=='all')a=a.filter(x=>(x.strategy_keys||[]).includes(strategyFilter.value));if(sort.value==='quality')a.sort((x,y)=>y.quality_score-x.quality_score);else if(sort.value==='res')a.sort((x,y)=>y.resonance_count-x.resonance_count);else if(sort.value==='change')a.sort((x,y)=>y.change_pct-x.change_pct);else a.sort((x,y)=>y.opportunity_score-x.opportunity_score);return a});
 const gainers=computed(()=>[...rows.value].sort((a,b)=>b.change_pct-a.change_pct).slice(0,12)); const losers=computed(()=>[...rows.value].sort((a,b)=>a.change_pct-b.change_pct).slice(0,12)); const watchRows=computed(()=>rows.value.filter(x=>watchlist.value.includes(x.symbol))); const riskRows=computed(()=>rows.value.filter(x=>x.tier==='S'||x.tier==='A').slice(0,20));
 const fmt=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'; const signed=x=>x==null?'—':(x>=0?'+':'')+Number(x).toFixed(2); const pct=x=>x==null?'—':(x>=0?'+':'')+Number(x).toFixed(2)+'%'; const money=x=>Number(x||0).toLocaleString('zh-CN');
 async function get(name){const r=await fetch(DATA+name+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(name);return r.json()}
 async function refresh(){if(loading.value)return;loading.value=true;lastRefresh.value='同步中';try{signals.value=await get('signals.json');market.value=await get('market.json');const n=await get('news.json');news.value=n.items||[];backtest.value=await get('backtest.json');lastRefresh.value='刚刚'}catch(e){lastRefresh.value='失败'}finally{loading.value=false}}
 async function open(r){selected.value=r;await nextTick();const el=document.getElementById('kchart');if(!el)return;try{const d=await get('stocks/'+r.symbol+'.json');const chart=echarts.init(el);const rows=d.klines.slice(-80);chart.setOption({animation:false,grid:{left:42,right:18,top:18,bottom:28},tooltip:{trigger:'axis'},xAxis:{type:'category',data:rows.map(x=>x.date),axisLabel:{color:'#888'}},yAxis:{scale:true,splitLine:{lineStyle:{color:getComputedStyle(document.documentElement).getPropertyValue('--line')}}},series:[{type:'candlestick',data:rows.map(x=>[x.open,x.close,x.low,x.high])}]});window.addEventListener('resize',()=>chart.resize())}catch(e){}}
 function toggleWatch(r){let a=[...watchlist.value];a=a.includes(r.symbol)?a.filter(x=>x!==r.symbol):[r.symbol,...a];watchlist.value=a;localStorage.setItem('quant_watchlist',JSON.stringify(a))};const isWatch=r=>watchlist.value.includes(r.symbol);function clearWatch(){watchlist.value=[];localStorage.removeItem('quant_watchlist')}
 function quickSearch(){const q=query.value.trim();if(!q)return;const r=rows.value.find(x=>x.symbol===q||x.name.includes(q));if(r){tab.value='signals';open(r)}}
 function toggleDark(){dark.value=!dark.value;document.documentElement.classList.toggle('dark',dark.value);localStorage.setItem('quant_dark',dark.value?'1':'0')}
 function savePrefs(){localStorage.setItem('quant_account',account.value);localStorage.setItem('quant_risk_pct',riskPct.value);localStorage.setItem('quant_max_pos',maxPos.value)}
 onMounted(()=>{document.documentElement.classList.toggle('dark',dark.value);refresh();setInterval(()=>{if(auto.value)refresh()},60000)});
 return {nav,tab,query,filter,tierFilter,strategyFilter,sort,signals,market,news,backtest,selected,watchlist,account,riskPct,maxPos,dark,auto,lastRefresh,loading,catalog,rows,healthy,breadth,breadthAdv,breadthDec,tier,count,top,filtered,gainers,losers,watchRows,riskRows,fmt,signed,pct,money,refresh,open,toggleWatch,isWatch,clearWatch,quickSearch,toggleDark,savePrefs}
}}).mount('#app');

const render=`<aside class="sidebar"><div class="brand"><b>智选 Quant</b><small>Personal Research Terminal · V2300</small></div><nav class="nav"><button v-for="n in nav" :class="{active:tab===n.id}" @click="tab=n.id"><span>{{n.icon}}</span>{{n.name}}</button></nav><div class="side-bottom">数据源 · Sina Finance<br>全市场 · {{market.universe||'—'}} 只<br>扫描 · {{market.scanned||'—'}} 只<br>更新 · {{fmt(market.updated_at)}}<br><span :class="healthy?'':'down'">● {{healthy?'数据链路正常':'等待数据'}}</span></div></aside><main class="main"><header class="topbar"><input class="search top-search" v-model="query" @keyup.enter="quickSearch" placeholder="搜索股票名称 / 代码，Enter 打开"><div class="top-actions"><span class="status">● {{healthy?'REAL DATA':'SYNCING'}}</span><button class="pill" @click="refresh">↻ {{lastRefresh}}</button><button class="iconbtn" @click="toggleDark">{{dark?'☀':'☾'}}</button></div></header><div class="content">
<section v-if="tab==='home'"><div class="hero"><div class="hero-main"><div class="eyebrow">MARKET REGIME · TODAY</div><h1>{{market.regime?.regime||'等待市场数据'}}</h1><p>{{market.regime?.directive||'数据同步完成后显示交易指令。'}}</p><div style="display:flex;align-items:end;gap:20px;margin-top:18px"><div><div class="big-score">{{market.regime?.score??'—'}}</div><div class="muted">市场温度 / 100</div></div><div class="notice" style="flex:1">建议仓位 <b>{{market.regime?.position||'—'}}</b><br>风险等级 <b>{{market.regime?.risk||'—'}}</b><br>平均涨跌 <b>{{market.regime?.avg_change_pct??'—'}}%</b></div></div></div><div class="card pad"><div class="eyebrow">MARKET BREADTH</div><div style="font-size:28px;font-weight:650;margin:10px 0">{{breadth.advancers||0}} <span class="muted" style="font-size:14px">上涨</span></div><div class="breadth"><div class="adv" :style="{width:breadthAdv+'%'}"></div><div class="dec" :style="{width:breadthDec+'%'}"></div></div><div class="kpi-line"><span>下跌</span><b>{{breadth.decliners||0}}</b></div><div class="kpi-line"><span>涨停附近</span><b class="up">{{breadth.limit_up||0}}</b></div><div class="kpi-line"><span>跌停附近</span><b class="down">{{breadth.limit_down||0}}</b></div></div></div><div class="grid g5"><div class="card metric"><div class="eyebrow">Universe</div><div class="value">{{market.universe||'—'}}</div></div><div class="card metric"><div class="eyebrow">Scanned</div><div class="value">{{market.scanned||'—'}}</div></div><div class="card metric"><div class="eyebrow">S Tier</div><div class="value blue">{{tier('S')}}</div></div><div class="card metric"><div class="eyebrow">A Tier</div><div class="value">{{tier('A')}}</div></div><div class="card metric"><div class="eyebrow">Risk H</div><div class="value down">{{tier('D')}}</div></div></div><div class="section-head"><div><div class="eyebrow">ACTIONABLE</div><h2>今日核心机会</h2></div><button class="btn secondary" @click="tab='signals'">查看全部</button></div><div class="card tablewrap"><StockTable :rows="top" @pick="open"/></div><div class="section-head"><h2>市场温度</h2></div><div class="grid g4"><div v-for="i in market.indices" class="card index-card"><b>{{i.name}}</b><div class="index-price">{{i.price}}</div><span :class="i.change_pct>=0?'up':'down'">{{signed(i.change_pct)}}%</span></div></div></section>
<section v-else-if="tab==='signals'"><div class="section-head"><div><div class="eyebrow">SIGNAL ENGINE</div><h2>智能选股</h2></div><div class="muted">A-H · 多因子评分 · 四维共振</div></div><div class="filterbar"><input v-model="filter" placeholder="筛选名称 / 代码"><select v-model="tierFilter"><option value="all">全部等级</option><option>S</option><option>A</option><option>B</option><option>D</option></select><select v-model="strategyFilter"><option value="all">全部策略</option><option v-for="(v,k) in catalog" :value="k">{{k}} {{v}}</option></select><select v-model="sort"><option value="opp">机会分</option><option value="quality">质量分</option><option value="res">共振数</option><option value="change">涨跌幅</option></select><button class="btn" @click="refresh">刷新</button></div><div class="card tablewrap"><StockTable :rows="filtered" @pick="open"/></div></section>
<section v-else-if="tab==='market'"><div class="section-head"><div><div class="eyebrow">MARKET MONITOR</div><h2>盘中监控</h2></div><div class="muted">最近成功快照；失败时不伪造实时值</div></div><div class="grid g4"><div v-for="i in market.indices" class="card index-card"><b>{{i.name}}</b><div class="index-price">{{i.price}}</div><span :class="i.change_pct>=0?'up':'down'">{{signed(i.change_pct)}}%</span></div></div><div class="section-head"><h2>强弱排名</h2></div><div class="grid g2"><div class="card tablewrap"><StockTable :rows="gainers" @pick="open"/></div><div class="card tablewrap"><StockTable :rows="losers" @pick="open"/></div></div></section>
<section v-else-if="tab==='watch'"><div class="section-head"><div><div class="eyebrow">PERSONAL LIST</div><h2>自选与跟踪</h2></div><button class="btn secondary" @click="clearWatch">清空</button></div><div class="card tablewrap"><StockTable :rows="watchRows" @pick="open"/><div v-if="!watchRows.length" class="empty">点击股票详情中的 ☆ 加入自选</div></div></section>
<section v-else-if="tab==='risk'"><div class="section-head"><div><div class="eyebrow">RISK MANAGEMENT</div><h2>组合风控</h2></div><div class="muted">研究与仓位计划，不连接券商</div></div><div class="grid g3"><div class="card pad"><div class="eyebrow">ACCOUNT NAV</div><input v-model.number="account" @change="savePrefs" class="search" style="margin-top:10px;width:100%"><div class="riskbox" style="margin-top:12px">单笔风险 <input v-model.number="riskPct" @change="savePrefs" class="risk-input" type="number" step="0.1"> %<br>最大持仓 <input v-model.number="maxPos" @change="savePrefs" class="risk-input" type="number"></div></div><div class="card pad"><div class="eyebrow">RISK BUDGET</div><div class="big-score" style="font-size:36px">{{money(account*riskPct/100)}}</div><div class="muted">单笔最大亏损预算</div></div><div class="card pad"><div class="eyebrow">POSITION RULE</div><div style="font-size:22px;font-weight:650">ATR × 1.5</div><div class="muted">止损；目标 ATR × 2.5<br>优先风险收益比 ≥ 1.5</div></div></div><div class="section-head"><h2>高质量信号</h2></div><div class="card tablewrap"><StockTable :rows="riskRows" @pick="open"/></div></section>
<section v-else-if="tab==='research'"><div class="section-head"><div><div class="eyebrow">RESEARCH LAB</div><h2>策略实验室</h2></div><div class="muted">真实历史样本 · 非写死收益</div></div><div v-if="backtest.status==='ok'" class="grid g5"><div class="card metric"><div class="eyebrow">Trades</div><div class="value">{{backtest.trades}}</div></div><div class="card metric"><div class="eyebrow">Win Rate</div><div class="value">{{pct(backtest.win_rate*100)}}</div></div><div class="card metric"><div class="eyebrow">Compounded</div><div class="value">{{pct(backtest.total_compounded_return*100)}}</div></div><div class="card metric"><div class="eyebrow">Max Drawdown</div><div class="value down">{{pct(backtest.max_drawdown*100)}}</div></div><div class="card metric"><div class="eyebrow">Sharpe Proxy</div><div class="value">{{backtest.sharpe_proxy??'—'}}</div></div></div><div v-else class="notice">回测等待数据：{{backtest.reason||'尚未生成'}}</div><div class="grid g2" style="margin-top:14px"><div class="card pad"><div class="eyebrow">METHODOLOGY</div><h3>滚动样本验证</h3><p class="muted" style="line-height:1.8">信号在历史时点独立计算，再向未来推进固定持有窗口，并加入固定双边成本代理。当前详细K线只保留高质量候选样本，结果用于研究，不等同于无幸存者偏差的全历史回测。</p></div><div class="card pad"><div class="eyebrow">A-H ARCHITECTURE</div><div v-for="(v,k) in catalog" class="kpi-line"><span><b>{{k}}</b> {{v}}</span><b>{{count(k)}}</b></div></div></div></section>
<section v-else-if="tab==='news'"><div class="section-head"><div><div class="eyebrow">INTELLIGENCE</div><h2>实时情报</h2></div><button class="btn" @click="refresh">刷新</button></div><div class="notice" style="margin-bottom:14px">仅展示实际抓取并通过规则校验的新闻；接口失败时保持空状态，不用模拟内容。</div><div class="grid g2"><article v-for="n in news" class="card pad"><div class="eyebrow">{{n.source}}</div><h3>{{n.title}}</h3><div class="muted">{{fmt(n.time)}}</div><a v-if="n.url" :href="n.url" target="_blank" rel="noopener" class="blue">阅读原文 →</a></article></div><div v-if="!news.length" class="card empty">暂无可验证新闻</div></section>
<section v-else><div class="section-head"><div><div class="eyebrow">SYSTEM</div><h2>设置与数据说明</h2></div></div><div class="grid g2"><div class="card pad"><h3>显示</h3><div class="kpi-line"><span>深色模式</span><button class="pill" @click="toggleDark">{{dark?'已开启':'已关闭'}}</button></div><div class="kpi-line"><span>自动刷新</span><button class="pill" @click="auto=!auto">{{auto?'60秒':'关闭'}}</button></div></div><div class="card pad"><h3>数据质量</h3><div class="kpi-line"><span>行情</span><b class="blue">Sina Finance</b></div><div class="kpi-line"><span>日K</span><b class="blue">真实日线</b></div><div class="kpi-line"><span>PE / PB / 市值</span><b>行情快照</b></div><div class="kpi-line"><span>D策略</span><b>量价成本代理</b></div></div></div><div class="notice" style="margin-top:14px">这是研究型量化终端，不构成投资建议。所有信号均是规则计算结果；“主力动能”与“筹码结构穿透”是量价代理，不代表真实资金账户或交易所筹码数据。系统不会自动下单。</div></section>
</div></main><nav class="mobile-nav"><button v-for="n in nav.slice(0,5)" :class="{active:tab===n.id}" @click="tab=n.id">{{n.icon}}<br>{{n.name}}</button></nav><div v-if="selected" class="modal" @click.self="selected=null"><div class="modal-card"><div class="modal-head"><div><b style="font-size:19px">{{selected.name}}</b><span class="stock-code">{{selected.symbol}}</span><span class="tag" :class="selected.tier==='S'?'s':selected.tier==='A'?'a':selected.tier==='D'?'d':''">{{selected.tier}}级</span></div><div><button class="iconbtn" @click="toggleWatch(selected)">{{isWatch(selected)?'★':'☆'}}</button><button class="iconbtn" @click="selected=null">×</button></div></div><div class="pad"><div class="grid g5"><div class="metric card"><div class="eyebrow">价格</div><div class="value">{{selected.price}}</div></div><div class="metric card"><div class="eyebrow">涨跌</div><div class="value" :class="selected.change_pct>=0?'up':'down'">{{signed(selected.change_pct)}}%</div></div><div class="metric card"><div class="eyebrow">共振</div><div class="value">{{selected.resonance_count}}</div></div><div class="metric card"><div class="eyebrow">机会</div><div class="value">{{selected.opportunity_score}}</div></div><div class="metric card"><div class="eyebrow">信心</div><div class="value">{{selected.signal_confidence}}</div></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><div id="kchart" class="chart"></div></div><div class="card pad"><div class="eyebrow">DECISION MAP</div><h3>{{selected.action_status}}</h3><p class="muted">{{selected.signal_reason}}</p><div class="kpi-line"><span>趋势</span><b>{{selected.trend_score}}</b></div><div class="kpi-line"><span>位置</span><b>{{selected.position_score}}</b></div><div class="kpi-line"><span>动量</span><b>{{selected.momentum_score}}</b></div><div class="kpi-line"><span>量能</span><b>{{selected.funds_score}}</b></div><div class="kpi-line"><span>止损</span><b class="down">{{selected.stop_loss}}</b></div><div class="kpi-line"><span>目标</span><b class="up">{{selected.target_price}}</b></div><div class="kpi-line"><span>风险收益比</span><b>{{selected.risk_reward}}</b></div><div class="notice" style="margin-top:12px">MA5 {{selected.ma5}} · MA10 {{selected.ma10}} · MA20 {{selected.ma20}} · MA60 {{selected.ma60}}<br>RSI {{selected.rsi14}} · MACD {{selected.macd_hist}} · KDJ {{selected.kdj_k}}/{{selected.kdj_d}}</div></div></div></div></div></div>`;
document.getElementById('app').innerHTML=render;