const {createApp,ref,computed,onMounted,nextTick}=Vue;
const BASE='./data/';
const nav=[['home','总览','⌂'],['signals','信号','◎'],['market','市场','◌'],['portfolio','组合','◇'],['research','研究','▣'],['news','情报','◈'],['settings','设置','⚙']];
function fmt(v){return v?new Date(v).toLocaleString('zh-CN',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function pct(v){return v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`}
function load(n){return fetch(BASE+n+'?v='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(n);return r.json()})}
const Table={props:['rows'],emits:['pick'],template:`<div class="table-scroll"><table><thead><tr><th>股票</th><th>价格</th><th>涨跌</th><th>等级</th><th>共振</th><th>机会</th><th>质量</th><th>止损</th><th>目标</th></tr></thead><tbody><tr v-for="r in rows" :key="r.symbol" @click="$emit('pick',r)"><td><b>{{r.name}}</b><small>{{r.symbol}}</small></td><td>{{r.price??'—'}}</td><td :class="r.change_pct>=0?'up':'down'">{{pct(r.change_pct)}}</td><td><i :class="'tier '+String(r.tier||'').toLowerCase()">{{r.tier||'—'}}</i></td><td>{{r.resonance_count??0}}</td><td><strong>{{r.opportunity_score??'—'}}</strong></td><td>{{r.quality_score??'—'}}</td><td>{{r.stop_loss??'—'}}</td><td>{{r.target_price??'—'}}</td></tr></tbody></table></div>`};
const tpl=`<div class="shell"><aside class="side"><div class="logo"><b>智选 Quant</b><span>V3100 · REAL DATA</span></div><nav><button v-for="n in nav" :class="{on:tab===n[0]}" @click="tab=n[0]"><em>{{n[2]}}</em>{{n[1]}}</button></nav><div class="source"><b>数据完整性</b><span :class="qPass?'ok':'bad'">● {{qPass?'VERIFIED':'BLOCKED'}}</span><small>主源 · Sina Finance</small><small>副源 · Tencent Finance</small><small>最后校验 · {{last}}</small><small>全市场 · {{market.universe||'—'}}</small></div></aside><main class="main"><header><div class="search"><span>⌕</span><input v-model="query" placeholder="搜索名称 / 代码"/></div><div class="actions"><span class="live" :class="qPass?'':'bad'">● {{qPass?'REAL DATA':'DATA BLOCKED'}}</span><button @click="refresh">↻</button><button @click="theme">{{dark?'☀':'☾'}}</button></div></header><div class="content">
<section v-if="tab==='home'"><div class="welcome"><div><span>MARKET COMMAND CENTER</span><h1>{{market.regime?.regime||'等待真实行情'}}</h1><p>{{market.regime?.directive||'数据链路通过校验后才允许产生交易信号。'}}</p></div><div class="temperature"><b>{{market.regime?.score??'—'}}</b><small>市场温度</small></div></div><div class="grid four"><div class="card"><small>数据源</small><strong>{{qPass?'双源交叉验证':'暂停生产信号'}}</strong></div><div class="card"><small>全市场</small><strong>{{market.universe||'—'}}</strong></div><div class="card"><small>已扫描</small><strong>{{market.scanned||'—'}}</strong></div><div class="card"><small>建议仓位</small><strong>{{market.regime?.position||'—'}}</strong></div></div><div class="grid two"><div class="card breadth"><div class="title"><span>市场宽度</span><b>{{advPct}}%</b></div><div class="bar"><i :style="{width:advPct+'%'}"></i></div><div class="split"><span>上涨 {{breadth.advancers||0}}</span><span>下跌 {{breadth.decliners||0}}</span></div></div><div class="card"><div class="title"><span>指数状态</span><small>真实快照</small></div><div class="indexes"><div v-for="i in market.indices"><b>{{i.name}}</b><strong>{{i.price??'—'}}</strong><span :class="i.change_pct>=0?'up':'down'">{{pct(i.change_pct)}}</span></div></div></div></div><div class="section"><div class="section-title"><div><small>ACTIONABLE</small><h2>高共振机会</h2></div><button @click="tab='signals'">全部信号 →</button></div><div class="card"><Table :rows="top" @pick="open"/></div></div></section>
<section v-else-if="tab==='signals'"><div class="section-title"><div><small>SIGNAL ENGINE · A-H</small><h2>智能选股</h2></div><div class="filters"><input v-model="query" placeholder="名称 / 代码"/><select v-model="filter"><option value="all">全部</option><option>S</option><option>A</option><option>B</option><option>D</option></select><select v-model="sort"><option value="opp">机会</option><option value="quality">质量</option><option value="res">共振</option></select></div></div><div class="card"><Table :rows="filtered" @pick="open"/></div></section>
<section v-else-if="tab==='market'"><div class="section-title"><div><small>MARKET INTELLIGENCE</small><h2>市场监控</h2></div><small>不使用浏览器模拟实时数据</small></div><div class="grid two"><div class="card"><div class="title"><span>申万行业</span><small>{{sector.status==='verified'?'VERIFIED':'UNAVAILABLE'}}</small></div><div class="sector" v-for="s in (sector.sectors||[]).slice(0,15)"><span>{{s.name}}</span><b :class="s.avg_change_pct>=0?'up':'down'">{{pct(s.avg_change_pct)}}</b></div></div><div class="card"><div class="title"><span>强势排名</span></div><Table :rows="top.slice(0,8)" @pick="open"/></div></div></section>
<section v-else-if="tab==='portfolio'"><div class="section-title"><div><small>RISK & POSITION</small><h2>组合计划</h2></div><small>研究模式 · 不连接券商</small></div><div class="grid three"><div class="card stat"><small>候选</small><strong>{{portfolio.candidates?.length||0}}</strong></div><div class="card stat"><small>状态</small><strong>RESEARCH ONLY</strong></div><div class="card stat"><small>自动下单</small><strong>OFF</strong></div></div><div class="card"><Table :rows="portfolio.candidates||[]" @pick="open"/></div></section>
<section v-else-if="tab==='research'"><div class="section-title"><div><small>RESEARCH LAB</small><h2>策略实验</h2></div></div><div class="grid three"><div class="card stat"><small>回测</small><strong>{{backtest.status||'—'}}</strong></div><div class="card stat"><small>Walk-forward</small><strong>{{walk.status||'—'}}</strong></div><div class="card stat"><small>历史快照</small><strong>{{walk.snapshots||0}}</strong></div></div><div class="card prose"><h3>研究纪律</h3><p>没有真实历史样本，就不显示虚构收益率。正式无幸存者偏差研究从系统启用日起持续积累全市场快照，并只使用当时可见信息。</p><p>当前回测结果如果显示为 not_ready，代表样本不足，而不是策略失败或成功。</p></div></section>
<section v-else-if="tab==='news'"><div class="section-title"><div><small>VERIFIED INTELLIGENCE</small><h2>实时情报</h2></div></div><div class="newslist"><article v-for="n in news.items||[]"><a :href="n.url" target="_blank">{{n.title}}</a><small>{{n.source}} · {{fmt(n.time)}}</small></article><div v-if="!(news.items||[]).length" class="empty">当前没有经过验证的新闻数据。</div></div></section>
<section v-else><div class="section-title"><div><small>SYSTEM</small><h2>系统设置</h2></div></div><div class="card prose"><h3>V3100 数据原则</h3><p>主行情源：Sina Finance。副行情源：Tencent Finance。日K优先使用腾讯前复权，失败才使用新浪真实日K；两者均失败则该股票不进入生产信号。</p><p>任何接口失败、过期、覆盖率不足、交叉验证异常，都显示 BLOCKED，不用随机数、固定值或旧数据冒充实时数据。</p></div></section></div></main><nav class="mobile"><button v-for="n in nav.slice(0,5)" :class="{on:tab===n[0]}" @click="tab=n[0]">{{n[2]}}<small>{{n[1]}}</small></button></nav><div v-if="selected" class="modal" @click.self="selected=null"><div class="detail"><header><div><b>{{selected.name}}</b><small>{{selected.symbol}} · {{selected.tier}}</small></div><button @click="selected=null">×</button></header><div class="detail-grid"><div><small>机会</small><strong>{{selected.opportunity_score}}</strong></div><div><small>质量</small><strong>{{selected.quality_score}}</strong></div><div><small>共振</small><strong>{{selected.resonance_count}}</strong></div><div><small>风险收益</small><strong>{{selected.risk_reward??'—'}}</strong></div></div><div id="chart" class="chart"></div><div class="reason"><b>{{selected.action_status}}</b><p>{{selected.signal_reason}}</p><span>止损 {{selected.stop_loss??'—'}} · 目标 {{selected.target_price??'—'}}</span></div></div></div></div>`;
document.getElementById('app').innerHTML=tpl;
createApp({components:{Table},setup(){
 const tab=ref('home'),dark=ref(localStorage.getItem('q_dark')==='1'),query=ref(''),signals=ref({items:[]}),market=ref({}),quality=ref({}),sector=ref({}),portfolio=ref({}),backtest=ref({}),walk=ref({}),news=ref({items:[]}),selected=ref(null),loading=ref(false),last=ref('—'),filter=ref('all'),sort=ref('opp');
 const rows=computed(()=>signals.value.items||[]); const filtered=computed(()=>{let a=[...rows.value];if(filter.value!=='all')a=a.filter(x=>x.tier===filter.value);if(sort.value==='quality')a.sort((x,y)=>(y.quality_score||0)-(x.quality_score||0));else if(sort.value==='res')a.sort((x,y)=>(y.resonance_count||0)-(x.resonance_count||0));else a.sort((x,y)=>(y.opportunity_score||0)-(x.opportunity_score||0));return a.filter(x=>!query.value||(`${x.name}${x.symbol}`).includes(query.value)).slice(0,500)}); const top=computed(()=>[...rows.value].filter(x=>['S','A'].includes(x.tier)).sort((a,b)=>(b.opportunity_score||0)-(a.opportunity_score||0)).slice(0,12)); const breadth=computed(()=>market.value.breadth||{}); const advPct=computed(()=>{let a=breadth.value.advancers||0,d=breadth.value.decliners||0;return a+d?Math.round(a/(a+d)*100):50}); const qPass=computed(()=>quality.value.status==='pass');
 async function refresh(){if(loading.value)return;loading.value=true;try{[signals.value,market.value,quality.value,sector.value,portfolio.value,backtest.value,walk.value,news.value]=await Promise.all([load('signals.json'),load('market.json'),load('data_quality.json'),load('sector_board.json'),load('portfolio_plan.json'),load('backtest.json'),load('walkforward.json'),load('news.json')]);last.value=fmt(quality.value.generated_at||market.value.updated_at)}catch(e){last.value='加载失败'}finally{loading.value=false}}
 async function open(r){selected.value=r;await nextTick();const el=document.getElementById('chart');if(!el)return;try{const d=await load(`stocks/${r.symbol}.json`),rs=(d.klines||[]).slice(-100),c=echarts.init(el);c.setOption({animation:false,grid:{left:45,right:18,top:20,bottom:30},tooltip:{trigger:'axis'},xAxis:{type:'category',data:rs.map(x=>x.date),axisLabel:{color:'#8e8e93',fontSize:10}},yAxis:{scale:true,splitLine:{lineStyle:{color:'#d2d2d7'}}},series:[{type:'candlestick',data:rs.map(x=>[x.open,x.close,x.low,x.high])}]})}catch(e){}}
 function theme(){dark.value=!dark.value;document.documentElement.classList.toggle('dark',dark.value);localStorage.setItem('q_dark',dark.value?'1':'0')}
 onMounted(()=>{document.documentElement.classList.toggle('dark',dark.value);refresh();setInterval(refresh,120000)}); return {nav,tab,dark,query,signals,market,quality,sector,portfolio,backtest,walk,news,selected,loading,last,filter,sort,rows,filtered,top,breadth,advPct,qPass,refresh,open,theme,pct,fmt}
}}).mount('#app');
